config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    root to: "homepage#index"

    devise_for :users, controllers: {
        registrations: 'users/registrations'
      }

    resource :job_seeker, path: 'jobseeker_profile', only: [:edit, :update, :show]
    resource :employer, path: 'employer_profile', only: [:edit, :update, :show]

    resources :resumes
    # FORM WIZARD
      # resources :steps, only: [:show, :update, :create], controller: 'steps_controllers/resume_steps'

    resources :vacancies
    resources :build_vacancy, only: [:update, :show], controller: 'steps_controllers/vacancy_steps'

    get '/resumes/skill/:id', to: 'resume_skills#show', as: 'resumes_skill'
    get '/vacancies/skill/:id', to: 'vacancy_skills#show', as: 'vacancies_skill'

    resource :about, only: :show

  end
end

app/models/employer.rb
class Employer < ApplicationRecord
  belongs_to :user
  has_many :vacancies, dependent: :destroy

  has_one_attached :logo

  def logo_thumbnail
    logo.variant(resize: '150x150!').processed
  end
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_employer, only: [:edit, :update, :show]
  # before_action :authenticate_user!

  def show
    if current_user.employer != nil
      # render the show screen
      render action: 'show'
    else
      redirect_to root_path, alert: 'Доступ запрещён'
    end
  end

  def edit
    if current_user.employer != nil
      # render the show screen
      render action: 'edit'
    else
      redirect_to root_path, alert: 'Доступ запрещён'
    end
  end

  def update
    if @employer.valid?
      @employer.update(employer_params)
      redirect_to employer_path, notice: 'Профиль успешно обновлён'
    else
      render action: 'edit', alert: 'Не удалось обновить профиль'
    end
  end

  private

  def set_employer
    @employer = current_user.employer
  end

  def employer_params
    params.require(:employer).permit(:logo,
                                     :name,
                                     :about_employer,
                                     :website,
                                     :email )
  end
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/views/employers/edit.html.erb
<div class="card mb-3">
    <div class="card-body">
        <%#= form_with model: @employer, local: true, url: company_path, method: :put do |f| %>
        <%= simple_form_for(@employer, method: :put, url: employer_path) do |f| %>


        <div class="image-upload" data-controller="photo-preview">
            <% if @employer.logo.attached? %>
                <%= image_tag @employer.logo, width: 200, class: "img-thumbnail company-logo-profile m-2", id: "photo-preview", data: { photo_preview_target: "photoPreview" } %>
            <% else %>
                <%= image_tag "logos/employer-default.svg", width: 200, class: "img-thumbnail company-logo-profile m-2", id: "photo-preview", data: { photo_preview_target: "photoPreview" } %>
            <% end %>

            <%= f.input :logo,
                        input_html: { class: 'd-none', data: { action: "click->photo-preview#photo_input", photo_preview_target: "photoInput" } },
                        label_html: { class: 'btn btn-outline-primary' },
                        label: t('.upload-photo'),
                        hint: t('.upload-photo-later') %>
        </div>

        <div class="mb-3">
            <%= f.label :name, t('.name'), class: "form-label" %>
            <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="mb-3">
            <%= f.label :about_employer, t('.about_employer'), class: "form-label" %>
            <%= f.text_area :about_employer, class: "form-control" %>
        </div>
        <div class="mb-3">
            <%= f.label :website, t('.website'), class: "form-label" %>
            <%= f.text_field :website, class: "form-control" %>
        </div>
        <div class="mb-3">
            <%= f.label :email, t('.email'), class: "form-label" %>
            <%= f.email_field :email, class: "form-control" %>
        </div>

            <%= f.submit t('.enter'), class: "btn btn-primary", data: {turbo: "false"} %>
        <% end %>
    </div>
</div>

app/views/employers/show.html.erb
<div class="row">
    <div class="col-lg-3 col-md-3"></div>
    <div class="col align-self-center col-lg-6 col-md-6">
<div class="card mb-3">
    <div class="card-body">
        <%= link_to t('.add_new_vacancy'), new_vacancy_path, class: "btn btn-primary btn-large" %>
    </div>
</div>
<div class="card mb-3">
    <div class="card-body">
        <div class="row">
            <div class="col-lg-4 col-md-5">

            <% if @employer.logo.attached? %>
                <%= image_tag @employer.logo_thumbnail, class: "img-thumbnail company-logo-profile m-2" %>
            <% else %>
                <%= image_tag "logos/employer-default.svg", width: 200, class: "img-thumbnail avatar-user-profile m-2", alt: "employer-default" %>
            <% end %>

            </div>
            <div class="col-lg-8 col-md-7">
               <h4><%= @employer.name %></h4>

                <p><%= t('.name') %>: <%= @employer.name %></p>
                <p><%= t('.about_employer') %>: <%= @employer.about_employer %></p>
                <p><%= t('.website') %>: <%= @employer.website %></p>
                <p><%= t('.email') %>: <%= @employer.email %></p>

                <%= link_to t('.edit_details'), edit_employer_path, class: "btn btn-primary", data: {turbo: "false"} %>
            </div>
        </div>



    </div>
</div>

</div>
<div class="col-lg-3 col-md-3"></div>
</div>