config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    root to: "homepage#index"

    devise_for :users, controllers: {
        registrations: 'users/registrations'
      }

    resource :job_seeker, path: 'jobseeker_profile', only: [:edit, :update, :show]
    resource :employer, path: 'employer_profile', only: [:edit, :update, :show]

    resources :resumes
    # FORM WIZARD
      # resources :steps, only: [:show, :update, :create], controller: 'steps_controllers/resume_steps'

    resources :vacancies
    resources :build_vacancy, only: [:update, :show], controller: 'steps_controllers/vacancy_steps'

    get '/resumes/skill/:id', to: 'resume_skills#show', as: 'resumes_skill'
    get '/vacancies/skill/:id', to: 'vacancy_skills#show', as: 'vacancies_skill'

    resource :about, only: :show

  end
end

app/models/resume.rb
class Resume < ApplicationRecord
  belongs_to :job_seeker

  has_one_attached :avatar

  has_many :work_experiences, dependent: :destroy
  has_many :educations, dependent: :destroy
  has_many :resume_skills, dependent: :destroy

  accepts_nested_attributes_for :work_experiences, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :educations, allow_destroy: true, reject_if: :all_blank

  has_many :skills, through: :resume_skills

  has_rich_text :summary

  default_scope { order(created_at: :desc) }

  def avatar_thumbnail
    avatar.variant(resize: '150x150!').processed
  end

  # def response
  #   Date.parse(super)
  # end

  # def response=(value)
  #   value = Date.new(value[1], value[2], value[3]) if value.is_a?(Hash)

  #   super(value.to_s)
  # end

  def skill_list=(skills_string)
    skill_names = skills_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_skills = skill_names.collect { |name| Skill.find_or_create_by(name: name) }
    self.skills = new_or_found_skills
  end

end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :is_not_jobseeker?, except: [:index, :show]
  before_action :set_resume, only: [:show, :edit, :update, :destroy]

  def show
  end

  def index
    # @resumes = Resume.all
    @resumes = resumes
    @query = query
  end

  def new
    current_job_seeker
    @resume = Resume.new
    # @resume.work_experiences.build
    # @resume.educations.build
  end

  def create
    @resume = Resume.create(resume_params)
    @resume.job_seeker_id = current_user.job_seeker.id

    if @resume.valid?
      @resume.save
      redirect_to resume_path(id: @resume.id), notice: "Резюмe успешно создано"
    else
      render action: "new", alert: "Создание резюме не удалось"
    end
  end

  def edit
    if !is_the_owner
      render @resume
    end
  end

  def update
    if @resume.update(resume_params)
      redirect_to resume_path(id: @resume.id), notice: "Резюмe успешно обновлено"
    else
      render action: "index", alert: "Обновление не удалось"
    end
  end

  def destroy
    if @resume.destroy
      redirect_to resumes_path, notice: "Успешно удалено!"
    else
      render action: 'show', alert: "Не удалось удалить объект"
    end
  end

  private

  def current_job_seeker
    @job_seeker = current_user.job_seeker
  end

  def set_resume
    @resume = Resume.find(params[:id])
  end

  def is_the_owner
    current_user.job_seeker.id == Resume.find(params[:id]).job_seeker_id
  end

  def is_not_jobseeker?
    if current_user.role != 'job_seeker'
      redirect_to root_path, alert: "Вы не соискатель, доступ запрещен"
    end
  end

  def resumes
    if query
      Resume.where("headline ILIKE ?", "%#{query}%")

      # Resume.joins(:skills).where("name ILIKE ?", "%#{query}%")
    else
      Resume.all
    end
  end

  def query
    params[:query]
  end

  def resume_params
    params.require(:resume).permit( :avatar,
                                    :first_name,
                                    :last_name,
                                    :age,
                                    :headline,
                                    :summary,
                                    :email,
                                    :phone_number,
                                    :country_of_residence,
                                    :city_or_state_of_residence,
                                    :relocation,
                                    :remote,
                                    :skill_list,
                                    work_experiences_attributes: [
                                      :id,
                                      :job_title,
                                      :description,
                                      :company,
                                      :country_of_work,
                                      :city_or_state_of_work,
                                      :i_currently_work_here,
                                      :from,
                                      :to,
                                      :_destroy],
                                    educations_attributes: [
                                      :id,
                                      :level_of_education,
                                      :field_of_study,
                                      :school_name,
                                      :country,
                                      :city_or_state,
                                      :currently_enrolled,
                                      :from,
                                      :to,
                                      :_destroy])
  end
end

app/helpers/resumes_helper.rb
module ResumesHelper
  def is_relocation(result)
    result == true ? t('.willing_relocate') : t('.not_willing_relocate') ;
  end

  def is_remote(result)
    result == true ? t('.willing_remote') : t('.not_willing_remote') ;
  end

  # "#{I18n.l(experience.from, format: "%B")}, #{experience.to.year}" %> - <%= "#{I18n.l(experience.to, format: "%B")}, #{experience.from.year}"
  def readable_month_and_year_experience(experience)
    if experience.from.present? && experience.from.year.present? && experience.to.present? && experience.to.year.present?
      month_from = I18n.l(experience.from, format: "%B")
      year_from = experience.from.year

      month_to = I18n.l(experience.to, format: "%B")
      year_to = experience.to.year

      return "#{month_from}, #{year_from} - #{month_to}, #{year_to}"
    elsif experience.from.present? && experience.from.year.present? || experience.i_currently_work_here == true && experience.from.present?
      month_from = I18n.l(experience.from, format: "%B")
      year_from = experience.from.year

      return "#{month_from}, #{year_from} - По настоящее время"
    else
      return "не указано"
    end
  end

  def readable_month_and_year_education(education)
    if education.from.present? && education.from.year.present? && education.to.present? && education.to.year.present?
      year_from = education.from.year

      year_to = education.to.year

      return "#{year_from} - #{year_to}"
    elsif education.from.present? && education.from.year.present? || currently_enrolled == true && education.from.present?
      year_from = education.from.year

      return "#{year_from} - По настоящее время"
    else
      return "не указано"
    end
  end


  def resume_skill_list
    @resume.skills.collect do |skill|
            skill.name
        end.join(", ")
  end
end

app/views/resumes/_education_fields.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">

    <div class="mb-3">
        <%= f.label :level_of_education, t('.level_of_education'), class: "form-label fw-bolder" %>
        <%= f.text_field :level_of_education, class: "form-control" %>
    </div>
    <div class="mb-3">
        <%= f.label :field_of_study, t('.field_of_study'), class: "form-label fw-bolder" %>
        <%= f.text_field :field_of_study , class: "form-control" %>
    </div>
    <div class="mb-3">
        <%= f.label :school_name, t('.school_name'), class: "form-label fw-bolder" %>
        <%= f.text_field :school_name , class: "form-control" %>
    </div>
    <div class="mb-3">
        <%= f.label :country, t('.country'), class: "form-label fw-bolder" %>
        <%= f.text_field :country , class: "form-control" %>
    </div>
    <div class="mb-3">
        <%= f.label :city_or_state, t('.city_or_state'), class: "form-label fw-bolder" %>
        <%= f.text_field :city_or_state , class: "form-control" %>
    </div>

    <p class="fw-bolder mb-1"><%= t('.time_period') %></p>
    <div class="form-check">
        <%= f.check_box :currently_enrolled, class: "form-check-input" %>
        <%= f.label :currently_enrolled, t('.currently_enrolled'), class: "form-check-label" %>
    </div>

    <div class="field" style="display:flex">
        <%= f.label :from, t('.from'), class: "form-label fw-bolder me-2" %>
        <%= f.date_select :from, { start_year: 1990, end_year: Time.now.year, order: [:month, :year], prompt: { month: t('.month'), year: t('.year') } }, { class: "date-select form-control pe-2 me-3 mb-2" } %>
    </div>
    <div class="field" style="display:flex">
        <%= f.label :to, t('.to'), class: "form-label fw-bolder me-2" %>
        <%= f.date_select :to, { start_year: 1990, end_year: Time.now.year, order: [:month, :year], prompt: { month: t('.month'), year: t('.year') } }, { class: "date-select form-control pe-2 me-3 mb-2" } %>
    </div>

    <%= link_to t('.remove_education'), '#', class: 'btn btn-danger', data: { action: 'nested-form#remove' } %>
    <!-- <button type="button" data-action="nested-form#remove">Remove education</button> -->

    <%= f.hidden_field :_destroy %>
</div>

app/views/resumes/_education_form.html.erb
<hr/><!-- Education -->
<div data-controller="nested-form" data-nested-form-wrapper-selector-value=".nested-form-wrapper">
    <p class="fw-lighter fs-4 mb-1"><%= t('.education') %></p>

    <template data-nested-form-target="template">
    <%= f.fields_for :educations, Education.new, child_index: 'NEW_RECORD' do |education_field| %>

        <%= render "education_fields", f: education_field %>

    <% end %>
    </template>

    <%= f.fields_for :educations do |education_field| %>
        <%= render "education_fields", f: education_field %>
    <% end %>

    <!-- Inserted elements will be injected before that target. -->
    <div data-nested-form-target="target"></div>

    <%= link_to t('.add_education'), '#', class: 'btn btn-primary', data: { action: 'nested-form#add' } %>
    <!-- <button type="button" data-action="nested-form#add">Add education</button> -->
</div>

app/views/resumes/_resume.html.erb
<article class="card shadow bg-body rounded mb-4 resume resume-<%= resume.id %>">
    <div class="card-header">
        <small class="d-inline-block mb-3 text-secondary border-bottom"><%= t('.posted')%>: <%= time_ago_in_words(resume.created_at) %> <%= t('.ago')%>.</small>
        <h3 class="mb-0"><%= link_to resume.headline, resume_path(id: resume.id), class: "title-link" %></h3>
    </div>
    <div class="card-body">

        <div class="row">
            <div class="col-4">
                <% if resume.avatar.attached? %>
                    <%= image_tag resume.avatar, width: 150, class: "rounded img-thumbnail m-2" %>
                <% else %>
                    <%= image_tag "jobseeker-default.png", width: 150, class: "rounded img-thumbnail m-2" %>
                <% end %>
            </div>
            <div class="col-8">
                <p class="fs-4"><%= "#{resume.first_name}" %> <%= "#{resume.last_name}" %></p>

                <p class="fw-light mb-0"><%= t('.age') %></p>
                <p><%= resume.age %></p>
                <p class="fw-light mb-0"><%= t('.current_location') %></p>
                <p><%= image_tag "logos/geo-alt-fill", class: "svg-icon" %>
                <%= resume.country_of_residence %>, <%= resume.city_or_state_of_residence %>
                <span class="inline-separator"> • </span><%= is_relocation(resume.relocation) %></p>

                <p class="fw-light mb-0"><%= t('.last_job') %></p>

                <% if resume.work_experiences.present? %>
                    <p><%= resume.work_experiences.last.company %><span class="inline-separator"> • </span><%= resume.work_experiences.last.job_title %></p>
                <% else %>
                    <p>ООО "Рога и Копыта"<span class="inline-separator"> • </span>Старший конюх</p>
                <% end %>
            </div>
        </div>

        <hr/>
        <p>
          <%= t('.skills')%>:

          <% resume.skills.each do |skill| %>
            <%= link_to skill.name, resumes_skill_path(id: skill) %>
          <% end %>
        </p>

        <%= link_to t('.read_more'), resume_path(id: resume.id), class: "btn btn-sm btn-outline-primary" %>
    </div>
</article>

app/views/resumes/_work_experience_fields.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
  <div class="mb-3">
    <%= f.label :job_title, t('.job_title'), class: "form-label fw-bolder" %>
    <%= f.text_field :job_title, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= f.label :description, t('.description'), class: "form-label fw-bolder" %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= f.label :company, t('.company'), class: "form-label fw-bolder" %>
    <%= f.text_field :company, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= f.label :country_of_work, t('.country_of_work'), class: "form-label fw-bolder" %>
    <%= f.text_field :country_of_work, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= f.label :city_or_state_of_work, t('.city_or_state_of_work'), class: "form-label fw-bolder" %>
    <%= f.text_field :city_or_state_of_work, class: "form-control" %>
  </div>

  <p class="fw-bolder mb-1"><%= t('.time_period') %></p>
  <div class="form-check">
    <%= f.check_box :i_currently_work_here, class: "form-check-input" %>
    <%= f.label :i_currently_work_here, t('.i_currently_work_here'), class: "form-check-label" %>
  </div>

  <div class="field" style="display:flex">
    <%= f.label :from, t('.from'), class: "form-label fw-bolder me-2" %>
    <%= f.date_select :from, { start_year: 1990, end_year: Time.now.year, order: [:month, :year], prompt: { month: t('.month'), year: t('.year') } }, { class: "date-select form-control pe-2 me-3 mb-2" } %>
  </div>
  <div class="field" style="display:flex">
    <%= f.label :to, t('.to'), class: "form-label fw-bolder me-2" %>
    <%= f.date_select :to, { start_year: 1990, end_year: Time.now.year, order: [:month, :year], prompt: { month: t('.month'), year: t('.year') } }, { class: "date-select form-control pe-2 me-3 mb-2" } %>
  </div>

  <%= link_to t('.remove_work_experience'), '#', class: 'btn btn-danger', data: { action: 'nested-form#remove' } %>
  <!-- <button type="button" data-action="nested-form#remove">Remove work experience</button> -->

  <%= f.hidden_field :_destroy %>
</div>

app/views/resumes/_work_experience_form.html.erb
<hr/><!-- Work Experience -->
<div data-controller="nested-form" data-nested-form-wrapper-selector-value=".nested-form-wrapper">
    <p class="fw-lighter fs-4 mb-1"><%= t('.work_experience') %></p>

    <template data-nested-form-target="template">
    <%= f.fields_for :work_experiences, WorkExperience.new, child_index: 'NEW_RECORD' do |work_experience_field| %>

        <%= render "work_experience_fields", f: work_experience_field %>

    <% end %>
    </template>

    <%= f.fields_for :work_experiences do |work_experience_field| %>
        <%= render "work_experience_fields", f: work_experience_field %>
    <% end %>

    <!-- Inserted elements will be injected before that target. -->
    <div data-nested-form-target="target"></div>

    <%= link_to t('.add_work_experience'), '#', class: 'btn btn-primary', data: { action: 'nested-form#add' } %>
    <!-- <button type="button" data-action="nested-form#add">Add work experience</button> -->
</div>

app/views/resumes/edit.html.erb
<div class="row">
    <div class="col-md-8 mb-3">
        <h2 class="mb-2"><%= t('.edit_resume') %></h2>

        <div class="shadow p-3 mb-5 bg-body rounded resume-padding">

            <%= simple_form_for(@resume, method: :put, url: resume_path) do |f| %>

                <% if @resume.errors.full_messages.any? %>
                  <% @resume.errors.full_messages.each do |error_message| %>
                    <%= error_message if @resume.errors.full_messages.first == error_message %> <br />
                  <% end %>
                <% end %>

                <%#= render "shared/validation-messages", object: f.object %>

                <!-- Personal Information -->
                <p class="fw-lighter fs-4 mb-1"><%= t('.personal_information') %></p>

                <div class="image-upload" data-controller="photo-preview">
                    <% if @resume.avatar.attached? %>
                        <%= image_tag @resume.avatar, width: 250, class: "resume-image img-thumbnail m-2", id: "photo-preview", data: { photo_preview_target: "photoPreview" } %>
                    <% else %>
                        <%= image_tag "jobseeker-default.png", width: 250, class: "resume-image img-thumbnail m-2", id: "photo-preview", data: { photo_preview_target: "photoPreview" } %>
                    <% end %>

                    <%= f.input :avatar,
                                input_html: { class: 'd-none', data: { action: "click->photo-preview#photo_input", photo_preview_target: "photoInput" } },
                                label_html: { class: 'btn btn-outline-primary mb-2' },
                                label: t('.upload-photo'),
                                hint: t('.upload-photo-later') %>
                </div>

                <div class="mb-3">
                    <%= f.label :first_name, t('.first_name'), class: "form-label fw-bolder" %>
                    <%= f.text_field :first_name, class: "form-control" %>
                </div>
                <div class="mb-3">
                    <%= f.label :last_name, t('.last_name'), class: "form-label fw-bolder" %>
                    <%= f.text_field :last_name, class: "form-control" %>
                </div>
                <div class="mb-3">
                    <%= f.label :age, t('.age'), class: "form-label fw-bolder" %>
                    <%= f.text_field :age, class: "form-control" %>
                </div>
                <div class="mb-3">
                    <%= f.label :headline, t('.headline'), class: "form-label fw-bolder" %>
                    <%= f.text_field :headline, class: "form-control" %>
                </div>
                <div class="mb-3">
                    <%= f.label :summary, t('.summary') %>
                    <%= f.rich_text_area :summary %>
                </div>
                <hr/>

                <!-- Location -->
                <div class="mb-3">
                    <%= f.label :country_of_residence, t('.country_of_residence'), class: "form-label fw-bolder" %>
                    <%= f.text_field :country_of_residence, class: "form-control" %>
                </div>
                <div class="mb-3">
                    <%= f.label :city_or_state_of_residence, t('.city_or_state_of_residence'), class: "form-label fw-bolder" %>
                    <%= f.text_field :city_or_state_of_residence, class: "form-control" %>
                </div>
                <p class="fw-bolder mb-1"><%= t('.relocation') %></p>
                <div class="form-check">
                    <%= f.check_box :relocation, class: "form-check-input"  %>
                    <%= f.label :relocation, t('.willing_relocate'), class: "form-check-label" %>
                </div>
                <p class="fw-bolder mb-1"><%= t('.remote') %></p>
                <div class="form-check">
                    <%= f.check_box :remote, class: "form-check-input" %>
                    <%= f.label :remote, t('.willing_remote'), class: "form-check-label" %>
                </div>

                <!-- Contact Information -->
                <p class="fw-lighter fs-4 mb-1"><%= t('.contact_information') %></p>
                <p class="fw-lighter"><small><%= t('.mail_phone_provided') %></small></p>
                <div class="mb-3">
                    <%= f.label :email, t('.email'), class: "form-label fw-bolder" %>
                    <%= f.text_field :email, class: "form-control" %>
                </div>
                <div class="mb-3">
                    <%= f.label :phone_number, t('.phone_number'), class: "form-label fw-bolder" %>
                    <%= f.text_field :phone_number, class: "form-control" %>
                </div>

                <%= render "work_experience_form", f: f %>

                <%= render "education_form", f: f %>

                <hr/><!-- Skills -->
                <div class="mb-3">
                  <%= f.label :skill_list, t('.skills'), class: "form-label fw-bolder mb-1" %>
                  <small class="fw-light">( <%= t('.enter_skills') %>: "," )</small>
                  <%= f.text_field :skill_list, class: "form-control", value: resume_skill_list %>
                </div>

                <%= f.submit t('.edit'), class: "btn btn-success" %>

            <% end %>
        </div>
    </div>
<div>

app/views/resumes/index.html.erb
<div class="row">
    <div class="col-lg-1 col-md-1 ml-auto mr-auto">

    </div>
    <div class="col-lg-7 col-md-6 ml-auto mr-auto">
        <div class="card shadow bg-body rounded mb-4">
            <div class="card-header">
                <h1 class="mb-0"><%= t('.resumes') %></h1>
            </div>
            <% if is_job_seeker? %>
            <div class="card-body">
                <%= link_to t('.add_new_resume'), new_resume_path, class: "btn btn-primary btn-large" %>
            </div>
            <% end %>
        </div>
        <%= form_with(
          url: resumes_path,
          method: :get,
          data: {
            controller: "submit-form",
            submit_form_target: "form",
            turbo_frame: :index
          }
        ) do |f| %>
          <%= f.text_field(
            :query,
            autofocus: true,
            autocomplete: "off",
            value: @query,
            placeholder: "Search",
            class: "form-control me-2",
            type: "search",
            data: {
              action: "input->submit-form#submit"
            }
          ) %>
        <% end %>
            <br/>
        <section id="resumes">
            <%= render @resumes %>
        </section>
            </div>

    <div class="col-lg-4 col-md-4 ml-auto mr-auto">
    </div>
</div>

<script type="text/javascript">
    function addEvent(elem, event, fn){
      if(elem.addEventListener){
        elem.addEventListener(event, fn, false);
      }else{
        elem.attachEvent("on" + event,
        function(){ return(fn.call(elem, window.event)); });
    }}

    var element = document.getElementById('query');

    addEvent(element,'focus',function(){
      var that = this;
      setTimeout(function(){ that.selectionStart = that.selectionEnd = 10000; }, 0);
    });
</script>

app/views/resumes/show.html.erb
<div class="page-content">
  <div class="container container-lg container-md container-sm">
    <div class="cover shadow-lg bg-white">
      <div class="cover-bg p-4 p-lg-5 text-white">
        <div class="row">

          <div class="col-lg-4 col-md-5">
            <div class="avatar hover-effect bg-white shadow-sm p-2">

              <% if @resume.avatar.attached? %>
                  <%#= image_tag(@job_seeker.avatar_thumbnail) %>
                  <%= image_tag @resume.avatar_thumbnail, width: 200, class: "" %>
              <% else %>
                  <%= image_tag "jobseeker-default.png", width: 200, class: "" %>
              <% end %>

            </div>
          </div>

          <div class="col-lg-8 col-md-7 text-center text-md-start">

            <h2 class="h1 mt-2" data-aos="fade-left" data-aos-delay="0"><%= "#{@resume.first_name}" %> <%= "#{@resume.last_name}" %></h2>

            <p data-aos="fade-left" data-aos-delay="100" class="fs-4"><%= @resume.headline %></p>

            <div class="d-print-none" data-aos="fade-left" data-aos-delay="200">
              <!-- <a class="btn btn-light text-dark shadow-sm mt-1 me-1" href="right-resume.pdf" target="_blank">Download CV</a> -->
              <!-- <a class="btn btn-success shadow-sm mt-1" href="#">Hire Me</a> -->
            </div>
          </div>
        </div>
      </div>
      <div class="about-section pt-5 px-4 px-lg-5 mt-1">
        <div class="row">

          <h2 class="h3 mb-3"><%= t('.about_me') %></h2>

          <!-- Personal Information -->
          <p class="fw-normal fs-5 mb-2"><%= t('.personal_information') %></p>

          <div class="col-sm-4">
            <p class="fw-light mb-0"><%= t('.age') %></p>
          </div>
          <div class="col-sm-8">
            <p><%= @resume.age %></p>
          </div>

          <div class="col-sm-4">
            <p class="fw-light mb-0"><%= t('.current_location') %></p>
          </div>
          <div class="col-sm-8">
            <p>
              <%= @resume.country_of_residence %>, <%= @resume.city_or_state_of_residence %>
            </p>
          </div>

          <div class="col-sm-4">
            <p class="fw-light mb-0"><%= t('.relocation') %></p>
          </div>
          <div class="col-sm-8">
            <p><%= is_relocation(@resume.relocation) %></p>
          </div>

          <div class="col-sm-4">
            <p class="fw-light mb-0"><%= t('.remote') %></p>
          </div>
          <div class="col-sm-8">
            <p><%= is_remote(@resume.remote) %></p>
          </div>

          <!-- Contact Information -->
          <p class="fw-normal fs-5 mb-2"><%= t('.contact_information') %></p>

          <div class="col-sm-4">
            <p class="fw-light mb-0"><%= t('.email') %></p>
          </div>
          <div class="col-sm-8">
            <p><%= @resume.email %></p>
          </div>

          <div class="col-sm-4">
            <p class="fw-light mb-0"><%= t('.phone_number') %></p>
          </div>
          <div class="col-sm-8">
            <p><%= @resume.phone_number %></p>
          </div>

        </div>
      </div>

      <hr class="d-print-none"/>

      <div class="about-section px-3 px-lg-4">
        <div class="row">
          <h2 class="h3 mb-3"><%= t('.summary') %></h2>

          <%= @resume.summary%>
        </div>
      </div>

      <hr class="d-print-none"/>

      <div class="skills-section px-3 px-lg-4">

        <h2 class="h3 mb-3"><%= t('.skills')%></h2>

        <div class="row">
          <p>
            <% @resume.skills.each do |skill| %>
              <%= link_to skill.name, resumes_skill_path(id: skill), class: "btn btn-primary mb-1" %>
            <% end %>
          </p>
        </div>
      </div>

      <hr class="d-print-none"/>

      <div class="work-experience-section px-3 px-lg-4">
        <h2 class="h3 mb-4"><%=t('.work_experience') %></h2>
        <div class="timeline">

          <% @resume.work_experiences.each do |experience| %>
          <div class="timeline-card timeline-card-primary card shadow-sm">
            <div class="card-body">
              <div class="h5 mb-1"><%= experience.job_title %> <span class="text-muted h6"><%=t('.at') %> <%= experience.company %></span></div>
              <div class="text-muted text-small mb-2"><%= readable_month_and_year_experience(experience) %> (<%= experience.country_of_work %>, <%= experience.city_or_state_of_work %>)</div>
              <div><%= experience.description %></div>
            </div>
          </div>
          <% end %>

        </div>
      </div>

    <hr class="d-print-none"/>

    <div class="page-break"></div>
      <div class="education-section px-3 px-lg-4 pb-4">
        <h2 class="h3 mb-4"><%=t('.education') %></h2>
        <div class="timeline">

          <% @resume.educations.each do |education| %>
          <div class="timeline-card timeline-card-success card shadow-sm">
            <div class="card-body">
              <div class="h5 mb-1"><%= education.level_of_education %><span class="inline-separator"> • </span><%= education.field_of_study %> <span class="text-muted h6"><%=t('.from') %> <%= education.school_name %></span>
              </div>

              <div class="text-muted text-small mb-2"><%= readable_month_and_year_education(education) %> (<%= education.country %>, <%= education.city_or_state %>)</div>
            </div>
          </div>
          <% end %>

        </div>
      </div>
      <div class="pb-5 ps-5">
        <%= link_to t('.edit_resume'), edit_resume_path, class: "btn btn-primary mb-1" %>

        <%= link_to t('.confirm_resume_remove'), resume_path, method: :delete, title: "", class: "btn btn-danger mb-1", data: { confirm: 'Вы действительно хотите удалить это резюме?' } %>
      </div>

    </div>
  </div>
</div>

<br/>
<br/>