config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    root to: "homepage#index"

    devise_for :users, controllers: {
        registrations: 'users/registrations'
      }

    resource :job_seeker, path: 'jobseeker_profile', only: [:edit, :update, :show]
    resource :employer, path: 'employer_profile', only: [:edit, :update, :show]

    resources :resumes
    # FORM WIZARD
      # resources :steps, only: [:show, :update, :create], controller: 'steps_controllers/resume_steps'

    resources :vacancies
    resources :build_vacancy, only: [:update, :show], controller: 'steps_controllers/vacancy_steps'

    get '/resumes/skill/:id', to: 'resume_skills#show', as: 'resumes_skill'
    get '/vacancies/skill/:id', to: 'vacancy_skills#show', as: 'vacancies_skill'

    resource :about, only: :show

  end
end

app/views/layouts/_alerts.html.erb
<div class="container-fluid">
  <% if notice.present? %>
    <div class="alert alert-info alert-dismissible fade show" role="alert">
      <%= notice %>
      <%= button_tag "", type: "button", class: "btn-close", "data-bs-dismiss": "alert", "aria-label": "Close" %>
    </div>
  <% end %>

  <% if alert.present? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <%= alert %>
      <%= button_tag "", type: "button", class: "btn-close", "data-bs-dismiss": "alert", "aria-label": "Close" %>
    </div>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<!-- Bootstrap Bundle with Popper (JS) -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<title>WorkFinder</title>

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_language_switcher.html.erb
<ul class="navbar-nav">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <%= embedded_svg("google-translate", class: "svg-icon") %>
        <span><%= t ('.languages') %></span>
      </a>
      <ul class="dropdown-menu bg-light" aria-labelledby="navbarDropdownMenuLink">
        <li class="">
            <%= link_to({ locale: 'en' }, class: "dropdown-item") do %>
                <%#= embedded_svg("us", class: "svg-flags") %> <!-- connect icon flag -->
                <span>English</span>
            <% end %>
        </li>
        <li>
            <%= link_to({ locale: 'ru' }, class: "dropdown-item") do %>
                <%#= embedded_svg("ru", class: "svg-flags") %>
                <span>Русский</span>
            <% end %>
        </li>
        <li>
            <%= link_to({ locale: 'de' }, class: "dropdown-item") do %>
                <%#= embedded_svg("de", class: "svg-flags") %>
                <span>Deutsche</span>
            <% end %>
        </li>
      </ul>
    </li>
</ul>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light p-2">
  <div class="container-fluid">
    <%= link_to t('.home'), root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <div class="navbar-nav">
        <%= link_to t('.resumes'), resumes_path, class: "nav-link" %>
      </div>
      <div class="navbar-nav">
        <%= link_to t('.vacancies'), vacancies_path, class: "nav-link" %>
      </div>
      <div class="navbar-nav">
        <%= link_to t('.about'), about_path, class: "nav-link" %>
      </div>
      <div class="ms-auto p-2 bd-highlight"> <!-- Positioning the navigation bar item in the far right corner -->
        <%= render 'layouts/profile' %>
      </div>
      <div class="text-start">
        <%= render 'layouts/language_switcher' %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_profile.html.erb
<ul class="navbar-nav">
  <% if user_signed_in? %>
  <li class="nav-item">
  <div class="dropdown text-end">
    <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser" data-bs-toggle="dropdown" aria-expanded="false">
      <% if is_job_seeker? %>

        <% if current_user.job_seeker.avatar.attached? %>
          <%= image_tag user_avatar(current_user.job_seeker, 40), class: "rounded-circle profile-icon", alt: "jobseeker-logo" %>
        <% else %>
          <%= image_tag "logos/jobseeker-default.svg", width: 40, class: "rounded-circle profile-icon", alt: "jobseeker-default" %>
        <% end %>

      <% elsif is_employer? %>

        <% if current_user.employer.logo.attached? %>
          <%= image_tag employer_logo(current_user.employer, 40), class: "rounded-circle profile-icon", alt: "employer-logo"%>
        <% else %>
          <%= image_tag "logos/employer-default.svg", width: 40, class: "rounded-circle profile-icon", alt: "employer-default" %>
        <% end %>

      <% end %>
    </a>
    <ul class="dropdown-menu dropdown-menu-end text-small" aria-labelledby="dropdownUser">
      <% if is_job_seeker? %>
          <li><%= link_to t('.show_profile'), job_seeker_path, class: "dropdown-item" %></li>
          <li><%= link_to t('.edit_profile'), edit_job_seeker_path, class: "dropdown-item" %></li>
        <% elsif is_employer? %>
          <li><%= link_to t('.show_profile'), employer_path, class: "dropdown-item" %></li>
          <li><%= link_to t('.edit_profile'), edit_employer_path, class: "dropdown-item" %></li>

        <% end %>
        <li><%= link_to t('.edit_account'), edit_user_registration_path, class: "dropdown-item" %></li>
        <li><hr class="dropdown-divider"></li>
        <li><%= link_to t('.sign_out'), destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
    </ul>
  </div>

  </li>
  <% else %>
    <%= link_to t('.sign_up'), new_user_registration_path, class: "btn btn-outline-success" %>
    <%= link_to t('.sign_in'), new_user_session_path, class: "btn btn-outline-success" %>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/header' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <br/>
      <%= render 'layouts/alerts' %>
      <%= yield %>
    </div>
  </body>
</html>